# nixpacks.toml — используется с break-system-packages для pip

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "git"
]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
