# nixpacks.toml — добавлены build-tools для C-расширений

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "git",
  "gcc",
  "python311Packages.buildPythonPackage"
]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py
