# nixpacks.toml — стабильная версия

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "git"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
