

[phases.setup]
nixPkgs = [
"python311",
"python311Packages.pip",
"git"
]


[phases.install]
cmds = [
"python3.11 -m pip install --upgrade pip",
"python3.11 -m pip install -r requirements.txt"
]


[start]
cmd = "python3.11 bot.py"
