# nixpacks.toml — билд без pip upgrade

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "git"
]

[phases.install]
cmds = [
  # Удалил upgrade pip — это ломает билд
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
