

# nixpacks.toml
# redeploy trigger 3 — стабильная версия


[phases.setup]
nixPkgs = [
"python311",
"python311Packages.pip",
"git"
]


[phases.install]
cmds = [
"python3.11 -m pip install --upgrade pip",
"python3.11 -m pip install -r requirements.txt"
]


[start]
cmd = "python3.11 bot.py"


# .env.example
TELEGRAM_TOKEN=your_telegram_bot_token
OPENAI_API_KEY=your_openai_key
OPENAI_MODEL=gpt-4o
WEBHOOK_URL=https://your-railway-subdomain.up.railway.app


# config.py
import os
from dotenv import load_dotenv
load_dotenv()


TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o")
WEBHOOK_URL = os.getenv("WEBHOOK_URL")


TARIFFS = {
"buy_start": {"messages": 20, "price": 10},
"buy_standard": {"messages": 200, "price": 30},
"buy_premium": {"messages": float("inf"), "price": 50}
}
